on: workflow_dispatch

permissions:
  contents: write

env:
  GH_TOKEN: ${{ secrets.TOKEN }}
  GH_BRANCH: ${{ secrets.GH_BRANCH }}
  GH_NAME: ${{ secrets.GH_NAME }}
  GH_REPO: ${{ secrets.GH_REPO }}
  GH_WORKFLOW: ${{ secrets.GH_WORKFLOW }}
  INVALIDATE_SECRET: ${{ secrets.INVALIDATE_SECRET }}
  SECRET_FIELD: ${{ secrets.SECRET_FIELD }}
  STRAPI_API: ${{ secrets.STRAPI_API }}
  STRAPI_API_TOKEN: ${{ secrets.STRAPI_API_TOKEN }}

jobs:
  update_blogs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.TOKEN }}

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Setup git
        run: |
          git config --global user.email nguyenquanglam3008@gmail
          git config --global user.name "lamnguyencse17"
          git config --global user.password ${{ secrets.TOKEN }}

      - name: Build blog
        run: pnpm build

      - name: Check for changes
        run: |
          git status --short
          if [[ $(git status --short) == "" ]]; then
            echo "No changes to push"
            exit 1
          fi

      - name: Push changes
        run: |
          git add .
          git commit -m "Update blog changes from CMS"
          git push origin main
